/* Generated by bin2c, do not edit manually */
#ifndef __v48k_h_included
#define __v48k_h_included

/* Contents of file Kimiko_Ishizaka_-_02_-_Variatio_1_a_1_Clav_0334-834.48k.raw */
extern const long int Kimiko_Ishizaka___02___Variatio_1_a_1_Clav_0334_834_48k_raw_size;
extern const unsigned char Kimiko_Ishizaka___02___Variatio_1_a_1_Clav_0334_834_48k_raw[96000];

#endif    /* __v48k_h_included */
